### ISSUE TITLE
Great work but is there any clearer examples on how to vendor your package directly into my `source/include` folder for my C extension.

### ISSUE THREAD

**Issue by jymchng** [ZeroIntensity/pyawaitable#25]
### Description:

Thank you for writing this, I think it is a great library and an important one, I am sure this will greatly enhance the Python ecosystem.

I have a question on vendoring your library into my own C extension as I would rather not to have too many build dependencies and relying on PYPI to distribute these include files.

Do you have any recommendation on how I can vendor them? Perhaps directly through `git submodule` or `git clone` into a `'source/include/'` directory? Apologies for this question as I am rather new to writing C extensions for Python.

**Comment by ZeroIntensity** [comment]
PyAwaitable directly supports vendored versions. See [this section](https://awaitable.zintensity.dev/#vendored-copies) of the docs, as well as the zip file shipped with [the release](https://github.com/ZeroIntensity/pyawaitable/releases/tag/v1.1.0).

**Comment by ZeroIntensity** [comment]
I realize that the docs aren't super clear. I'm working on an update.
